typography_spectrum: 0.4504796299152076
color:
  brandStrength: 0.24214988481253386
  lightness: 0.9392130500636995
  saturation: 0.004602872533723712
  rhythmicContrast: 0.06830585491843522
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.9762320031877607
name: A Modern Education
title: A Modern Education
description: the future of education
