typography_spectrum: 0.4927385638002306
color:
  brandStrength: 0.12460945593193173
  lightness: 0.8216380316298455
  saturation: 0.9286311403848231
  rhythmicContrast: 0.23353591142222285
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8592575062066317
name: A Modern Education
navigation:
  - name: About Me
    id: a9ee1417-5abe-44df-823a-2678b4324bde
    type: content
title: A Modern Education
description: the future of education
