layout_spectrum: 0.9762320031877607
typography_spectrum: 0.4504796299152076
color:
  brandStrength: 0.24214988481253386
  lightness: 0.9392130500636995
  saturation: 0.004602872533723712
  rhythmicContrast: 0.06830585491843522
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
name: A Modern Education
